package vu.lt.mybatis.model;

public class ReservationRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    private Long reservationsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    private Long reservedroomsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public Long getReservationsId() {
        return reservationsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @param reservationsId the value for PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public void setReservationsId(Long reservationsId) {
        this.reservationsId = reservationsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public Long getReservedroomsId() {
        return reservedroomsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @param reservedroomsId the value for PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public void setReservedroomsId(Long reservedroomsId) {
        this.reservedroomsId = reservedroomsId;
    }
}