package vu.lt.mybatis.model;

import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.ENDDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.STARTDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    private Date startdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.ID
     *
     * @return the value of PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.ID
     *
     * @param id the value for PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.ENDDATE
     *
     * @return the value of PUBLIC.RESERVATION.ENDDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.ENDDATE
     *
     * @param enddate the value for PUBLIC.RESERVATION.ENDDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.STARTDATE
     *
     * @return the value of PUBLIC.RESERVATION.STARTDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.STARTDATE
     *
     * @param startdate the value for PUBLIC.RESERVATION.STARTDATE
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
}