package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.ReservationRoom;

@Mapper
public interface ReservationRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    int insert(ReservationRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    List<ReservationRoom> selectAll();
}