package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Reservation;

import java.util.List;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    Reservation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    List<Reservation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Mar 31 17:17:07 EEST 2019
     */
    int updateByPrimaryKey(Reservation record);
}